Repository sambanova/ai-starter-kit, pull requests merged in 2024-10, with the labels that each got.

#383 Feature: Add test suite to github actions and pre commit ruff
  .github/workflows/python_checks.yml
  .pre-commit-config.yaml
  CoE_jump_start/requirements.txt
  Makefile
  base-requirements.txt
  benchmarking/requirements.txt
  data_extraction/requirements.txt
  data_extraction/requirementsPaddle.txt
  edgar_qna/requirements.txt
  enterprise_knowledge_retriever/requirements.txt
  eval_jumpstart/requirements.txt
  financial_assistant/requirements.txt
  financial_assistant/tests/financial_assistant_test.py
  financial_assistant/tests/github_pull_request_test.py
  fine_tuning_embeddings/requirements.txt
  fine_tuning_sql/requirements.txt
  function_calling/requirements.txt
  image_search/requirements.txt
  image_search/tests/image_search_test.py
  multimodal_knowledge_retriever/requirements.txt
  post_call_analysis/requirements.txt
  prompt_engineering/requirements.txt
  ruff.toml
  sambanova_scribe/requirements.txt
  search_assistant/requirements.txt
  tests/test_framework.py
  utils/eval/app.py
  utils/eval/rag_eval.py
  utils/model_wrappers/api_gateway.py
  utils/model_wrappers/langchain_llms.py
  utils/model_wrappers/multimodal_models.py
  utils/parsing/unstructured-api/prepline_general/api/app.py
  utils/prod/update_config.py
  utils/synthetic_data_gen/src/synthetic_data_gen.py
  utils/vectordb/vector_db.py
  web_crawled_data_retriever/requirements.txt
  yoda/requirements.txt
Labels: feature

#393 Improvement: Production Config and Makefile improvements
  Makefile
  run_tests.sh
  tests/test_framework.py
  utils/prod/update_config.py
Labels: improvement

#396 Bugfix: updated base-requirements.txt to have llama-index
  base-requirements.txt
Labels: bugfix

#398 Fixed bug in `include_usage` stream option for SambaNova Cloud api re…
  benchmarking/src/llmperf/sambanova_client.py
Labels: bugfix

#397 Improvement/docker testing workflow branch: First pass at building global testing workflow via docker and github actions
  .dockerignore
  .github/workflows/docker-build-and-test.yml
Labels: improvement

#402 Feature: add function calling quickstart notebook
  quickstart/function_calling_calculate.ipynb
Labels: feature

#400 Improvement: Function calling extra configs for streamlit prod mode
  function_calling/config.yaml
  function_calling/prompts/streamlit_preset_queries.yaml
  function_calling/streamlit/app.py
Labels: bugfix, improvement

#399 Improvement: Image search environment variables
  image_search/README.md
  image_search/src/image_search.py
Labels: improvement

#388 Improvement: Refactor SambaStudio wrapper and OpenAI compatible api support added
  README.md
  data_extraction/notebooks/retrieval_from_pdf_tables.ipynb
  fine_tuning_sql/notebooks/5_inference_sql_model.ipynb
  function_calling/notebooks/function_calling_guide.ipynb
  multimodal_knowledge_retriever/notebooks/2_multimodal_rag.ipynb
  post_call_analysis/notebooks/analysis.ipynb
  quickstart/llms_get_started.ipynb
  search_assistant/notebooks/search_asistant.ipynb
  utils/eval/eval_main.py
  utils/eval/rag_eval.py
  utils/guardrails/guard.ipynb
  utils/guardrails/guard.py
  utils/model_wrappers/api_gateway.py
  utils/model_wrappers/langchain_chat_models.py
  utils/model_wrappers/langchain_llms.py
  utils/model_wrappers/usage.ipynb
  web_crawled_data_retriever/notebooks/web_crawled_data_retriever.ipynb
Labels: documentation, improvement

#406 Improvement/docker testing workflow branch:
  .github/workflows/docker-build-and-test.yml
  Makefile
  base-requirements.txt
  enterprise_knowledge_retriever/streamlit/config.toml
  tests/test_framework.py
  utils/prod/update_config.py
Labels: improvement

#405 Improvement: mutimodal kit and quickstart minor changes
  multimodal_knowledge_retriever/notebooks/1_multimodal_get_started.ipynb
  multimodal_knowledge_retriever/streamlit/app.py
  quickstart/multimodal_get_started.ipynb
Labels: improvement

#392 Improvement: Benchmarking kit with SambaStudio URL
  benchmarking/README.md
  benchmarking/src/llmperf/models.py
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/src/performance_evaluation.py
  benchmarking/streamlit/app.py
  benchmarking/streamlit/pages/chat_performance_st.py
  benchmarking/streamlit/pages/custom_performance_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
  benchmarking/streamlit/streamlit_utils.py
  utils/visual/env_utils.py
Labels: improvement

#404 Improvement: synthetic data gen notebooks updated
  utils/synthetic_data_gen/notebooks/data/SambaNova_Dataflow.pdf
  utils/synthetic_data_gen/notebooks/quickstart_synthetic_data_gen.ipynb
  utils/synthetic_data_gen/notebooks/usage.ipynb
  utils/synthetic_data_gen/src/synthetic_data_gen.py
Labels: improvement

#401 Feature/benchmarking openai compatible
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/src/performance_evaluation.py
  benchmarking/streamlit/pages/custom_performance_eval_st.py
Labels: feature

#408 Documentation: Update GETTING_STARTED.md
  GETTING_STARTED.md
Labels: documentation

#403 Improvement: Separate `src` from `streamlit` in the financial assistant
  financial_assistant/constants.py
  financial_assistant/src/exceptions.py
  financial_assistant/src/llm.py
  financial_assistant/src/retrieval.py
  financial_assistant/src/tools.py
  financial_assistant/src/tools_database.py
  financial_assistant/src/tools_filings.py
  financial_assistant/src/tools_pdf_generation.py
  financial_assistant/src/tools_stocks.py
  financial_assistant/src/tools_yahoo_news.py
  financial_assistant/src/utilities.py
  financial_assistant/streamlit/app.py
  financial_assistant/streamlit/app_financial_filings.py
  financial_assistant/streamlit/app_pdf_report.py
  financial_assistant/streamlit/app_stock_data.py
  financial_assistant/streamlit/app_stock_database.py
  financial_assistant/streamlit/app_yfinance_news.py
  financial_assistant/streamlit/constants.py
  financial_assistant/streamlit/utilities/save_yfinance_columns_to_json.py
  financial_assistant/streamlit/utilities_app.py
  financial_assistant/streamlit/utilities_methods.py
  financial_assistant/tests/financial_assistant_test.py
Labels: improvement

#410 Improvement: Decouple src and UI streamlit code for EKR
  enterprise_knowledge_retriever/src/bulkQA.py
  enterprise_knowledge_retriever/src/document_retrieval.py
  enterprise_knowledge_retriever/streamlit/app.py
  enterprise_knowledge_retriever/tests/ekr_test.py
Labels: improvement

#391 Feature: Fine-tuning util
  .gitignore
  utils/fine_tuning/Readme.md
  utils/fine_tuning/config.yaml
  utils/fine_tuning/config_embeddings.yaml
  utils/fine_tuning/src/sambastudio_utils.py
  utils/fine_tuning/src/snsdk_wrapper.py
  utils/fine_tuning/usage.ipynb
Labels: feature

#415 Fixed bug related to runs with long total tokens (up to 60k)
  benchmarking/prompts/user-prompt_template.yaml
  benchmarking/src/performance_evaluation.py
Labels: bugfix

#412 Improvement: multimodal ekr remove envs and oudtaed models for llama3.2 11B launch
  multimodal_knowledge_retriever/src/multimodal_rag.py
  multimodal_knowledge_retriever/streamlit/app.py
  utils/model_wrappers/multimodal_models.py
Labels: improvement

#418 added in to run at every pr opened, synchronize, reopened
  .github/workflows/docker-build-and-test.yml
Labels: improvement

#411 Feature: Eval kit refactor
  eval_jumpstart/README.md
  eval_jumpstart/data/eval_data.csv
  eval_jumpstart/notebooks/eval_llm.ipynb
  eval_jumpstart/notebooks/eval_rag.ipynb
  eval_jumpstart/notebooks/example_rag_pipeline.py
  eval_jumpstart/notebooks/simple_llm_answers.py
  eval_jumpstart/requirements.txt
  utils/eval/app.py
  utils/eval/config.yaml
  utils/eval/dataset.py
  utils/eval/eval_main.py
  utils/eval/evaluate.py
  utils/eval/evaluator.py
  utils/eval/llm.py
  utils/eval/prompts/judge_prompt.py
  utils/eval/rag_eval.py
  utils/eval/rag_pipeline.py
  utils/eval/simple_llm_answers.py
Labels: feature

#416 Improvement: EKR multiturn conversation, and chat models added
  enterprise_knowledge_retriever/config.yaml
  enterprise_knowledge_retriever/prompts/conversation-summary.yaml
  enterprise_knowledge_retriever/prompts/final_chain_prompt.yaml
  enterprise_knowledge_retriever/prompts/llama7b-knowledge_retriever-custom_qa_prompt.yaml
  enterprise_knowledge_retriever/prompts/multiturn_custom_condensed_query.yaml
  enterprise_knowledge_retriever/prompts/qa_prompt.yaml
  enterprise_knowledge_retriever/src/bulkQA.py
  enterprise_knowledge_retriever/src/document_retrieval.py
  enterprise_knowledge_retriever/streamlit/app.py
  utils/model_wrappers/api_gateway.py
Labels: improvement, feature

#426 improvement: add output fixing parsers
  post_call_analysis/config.yaml
  post_call_analysis/src/analysis.py
  utils/model_wrappers/api_gateway.py
Labels: improvement

#422 Bugfix: prod_mode credentials
  financial_assistant/constants.py
  financial_assistant/llm_model.py
  financial_assistant/src/llm.py
  financial_assistant/src/retrieval.py
  financial_assistant/src/tools.py
  financial_assistant/src/tools_database.py
  financial_assistant/src/tools_pdf_generation.py
  financial_assistant/src/tools_stocks.py
  financial_assistant/src/utilities.py
  financial_assistant/streamlit/app.py
  financial_assistant/streamlit/app_financial_filings.py
  financial_assistant/streamlit/app_pdf_report.py
  financial_assistant/streamlit/app_stock_data.py
  financial_assistant/streamlit/app_stock_database.py
  financial_assistant/streamlit/app_yfinance_news.py
  financial_assistant/streamlit/utilities_app.py
  financial_assistant/streamlit/utilities_methods.py
  multimodal_knowledge_retriever/streamlit/app.py
  tests/test_framework.py
  utils/eval/evaluator.py
  utils/eval/llm.py
  utils/prod/update_config.py
Labels: bugfix

#428 Documentation: minor changes to function calling notebook
  function_calling/notebooks/function_calling_guide.ipynb
Labels: bugfix, documentation
