Repository sambanova/ai-starter-kit, pull requests merged in 2024-11, with the labels that each got.

#429 Bugfix: Store credential in the streamlit session state
  financial_assistant/llm_model.py
  financial_assistant/src/exceptions.py
  financial_assistant/src/llm.py
  financial_assistant/src/retrieval.py
  financial_assistant/src/tools.py
  financial_assistant/src/tools_database.py
  financial_assistant/src/tools_pdf_generation.py
  financial_assistant/src/tools_stocks.py
  financial_assistant/streamlit/app.py
  financial_assistant/streamlit/app_financial_filings.py
  financial_assistant/streamlit/app_pdf_report.py
  financial_assistant/streamlit/app_stock_data.py
  financial_assistant/streamlit/app_stock_database.py
  financial_assistant/streamlit/app_yfinance_news.py
  financial_assistant/streamlit/llm_model.py
  financial_assistant/streamlit/utilities_app.py
  financial_assistant/streamlit/utilities_methods.py
  financial_assistant/tests/financial_assistant_test.py
Labels: bugfix

#433 Improvement: function calling ui improvements
  function_calling/streamlit/app.py
  function_calling/streamlit/app_description.yaml
Labels: improvement

#427 Feature: mixpanel events
  benchmarking/streamlit/app.py
  benchmarking/streamlit/pages/chat_performance_st.py
  benchmarking/streamlit/pages/custom_performance_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
  enterprise_knowledge_retriever/README.md
  enterprise_knowledge_retriever/streamlit/app.py
  financial_assistant/streamlit/app.py
  financial_assistant/streamlit/app_financial_filings.py
  financial_assistant/streamlit/app_pdf_report.py
  financial_assistant/streamlit/app_stock_data.py
  financial_assistant/streamlit/app_stock_database.py
  financial_assistant/streamlit/app_yfinance_news.py
  financial_assistant/streamlit/utilities_app.py
  function_calling/streamlit/app.py
  multimodal_knowledge_retriever/streamlit/app.py
  sambanova_scribe/streamlit/app.py
  search_assistant/README.md
  search_assistant/config.yaml
  search_assistant/src/search_assistant.py
  search_assistant/streamlit/app.py
  utils/events/mixpanel.py
Labels: feature

#435 Bugfix: Patch to reduce tokenizer decoding on template prompt
  benchmarking/requirements.txt
  benchmarking/run_custom_dataset.sh
  benchmarking/src/performance_evaluation.py
Labels: bugfix

#438 Delete outdated kits
  GETTING_STARTED.md
  README.md
  edgar_qna/README.md
  edgar_qna/api/server.py
  edgar_qna/config.yaml
  edgar_qna/data/company_tickers.json
  edgar_qna/docker-compose.yaml
  edgar_qna/docker/Dockerfile
  edgar_qna/docs/edgar_comparative_qa_demo.png
  edgar_qna/docs/edgar_multiturn_demo.png
  edgar_qna/docs/edgar_qa_demo.png
  edgar_qna/docs/edgar_qa_docker.png
  edgar_qna/notebooks/1_edgar_assistant.ipynb
  edgar_qna/notebooks/2_edgar_comparative_qna.ipynb
  edgar_qna/prompts/edgar_comparative_qna-answering_and_summarization_prompt.yaml
  edgar_qna/prompts/edgar_comparative_qna-query_decomposition_prompt.yaml
  edgar_qna/prompts/edgar_multiturn-custom_condensed_question.yaml
  edgar_qna/prompts/edgar_multiturn-custom_qa_prompt.yaml
  edgar_qna/prompts/edgar_qna.yaml
  edgar_qna/requirements.txt
  edgar_qna/src/edgar_sec.py
  edgar_qna/streamlit/app_chat.py
  edgar_qna/streamlit/app_comparative_chat.py
  edgar_qna/streamlit/app_qna.py
Labels: bugfix, documentation

#442 Improvement: code copilot update
  code_copilot/README.md
  code_copilot/config.json
  code_copilot/config.ts
Labels: bugfix, improvement

#431 Improvement: Decouple kit
  search_assistant/src/search_assistant.py
  search_assistant/streamlit/app.py
  search_assistant/tests/search_assistant_test.py
Labels: improvement

#445 Bugfix: Uncomment lines for financial_assistant in tests
  tests/test_framework.py
Labels: bugfix

#437 Feature: Add utils functions and unit tests to test S3 buckets
  base-requirements.txt
  utils/prod/s3_utils.py
  utils/prod/tests/test_s3_utils.py
Labels: feature

#446 Improvement: function calling quickstart
  quickstart/function_calling_calculate.ipynb
  quickstart/function_calling_get_started.ipynb
  quickstart/llms_get_started.ipynb
  utils/model_wrappers/langchain_chat_models.py
Labels: bugfix, improvement

#449 bugfix: function calling kit not sowing chat history
  function_calling/streamlit/app.py
Labels: bugfix

#443 First pass at Contributing Guidelines for AISK
  CONTRIBUTING.md
Labels: improvement

#451 Bugfix: session state variable not found bug in prod mode
  function_calling/streamlit/app.py
Labels: bugfix

#447 Feature: EKR vectordb option
  enterprise_knowledge_retriever/README.md
  enterprise_knowledge_retriever/config.yaml
  enterprise_knowledge_retriever/src/document_retrieval.py
  utils/vectordb/vector_db.py
Labels: feature

#440 Feature: bind tools and structured output sstudio wrapper
  utils/model_wrappers/langchain_chat_models.py
  utils/model_wrappers/usage.ipynb
Labels: feature

#424 Feature: Model wrapper and api unittest
  utils/model_wrappers/tests/model_wrappers_test.py
  utils/model_wrappers/tests/schemas.py
  utils/model_wrappers/tests/test_config.yaml
Labels: feature

#454 improvement: byoc and finetunig util updates
  utils/byoc/README.md
  utils/byoc/config.yaml
  utils/byoc/requirements.txt
  utils/byoc/src/snsdk_byoc_wrapper.py
  utils/byoc/usage.ipynb
  utils/fine_tuning/Readme.md
  utils/fine_tuning/config.yaml
  utils/fine_tuning/requirements.txt
  utils/fine_tuning/src/sambastudio_utils.py
  utils/fine_tuning/src/snsdk_wrapper.py
  utils/fine_tuning/usage.ipynb
Labels: bugfix, improvement

#457 Feature: e2e byoc and finetuning base kit
  .gitignore
  e2e_fine_tuning/README.md
  e2e_fine_tuning/checkpoints_config.yaml
  e2e_fine_tuning/dataset_config.yaml
  e2e_fine_tuning/deploy_config.yaml
  e2e_fine_tuning/finetune_config.yaml
  e2e_fine_tuning/notebooks/1_checkpoints.ipynb
  e2e_fine_tuning/notebooks/2_datasets.ipynb
  e2e_fine_tuning/notebooks/3_fine_tuning.ipynb
  e2e_fine_tuning/notebooks/4_deploy.ipynb
  e2e_fine_tuning/requirements.txt
  utils/byoc/README.md
  utils/byoc/config.yaml
  utils/byoc/src/snsdk_byoc_wrapper.py
  utils/fine_tuning/Readme.md
  utils/fine_tuning/src/sambastudio_utils.py
  utils/fine_tuning/src/snsdk_wrapper.py
  utils/fine_tuning/usage.ipynb
Labels: improvement, feature

#459 Bugfix: Change cache path to save in GCP persistent storage
  .gitignore
  financial_assistant/constants.py
  financial_assistant/src/llm.py
Labels: bugfix

#452 Improvement: decouple streamlit and src function calling kit
  README.md
  function_calling/notebooks/usage.ipynb
  function_calling/src/function_calling.py
  function_calling/src/tools.py
  function_calling/streamlit/app.py
  function_calling/tests/fc_test.py
Labels: improvement

#460 improvement: byoc / fune-tuning requirements updated
  utils/byoc/requirements.txt
  utils/fine_tuning/requirements.txt
Labels: improvement

#463 Bugfix: Scratch folder at container level.
  financial_assistant/constants.py
Labels: bugfix
