Repository sambanova/ai-starter-kit, pull requests merged in 2024-12, with the labels that each got.

#462 bugfix: e2e finetuning byoc kit
  e2e_fine_tuning/notebooks/1_checkpoints.ipynb
  e2e_fine_tuning/notebooks/2_datasets.ipynb
  e2e_fine_tuning/notebooks/3_fine_tuning.ipynb
  e2e_fine_tuning/notebooks/4_deploy.ipynb
Labels: bugfix

#458 Feature: Script and notebook needed for benchmarking and evaluation studios
  benchmarking/benchmarking_studio/compiler_results.ipynb
  benchmarking/benchmarking_studio/script.py
  benchmarking/src/performance_evaluation.py
Labels: improvement

#466 fbugfix: fix sncloud credentials prompt when using sambastudio
  enterprise_knowledge_retriever/streamlit/app.py
  function_calling/src/function_calling.py
  function_calling/streamlit/app.py
  function_calling/tests/fc_test.py
  multimodal_knowledge_retriever/streamlit/app.py
  search_assistant/streamlit/app.py
Labels: bugfix

#465 Improvement: Path names in session state and code cleanup
  financial_assistant/src/tools_database.py
  financial_assistant/src/tools_filings.py
  financial_assistant/src/tools_pdf_generation.py
  financial_assistant/src/tools_stocks.py
  financial_assistant/src/tools_yahoo_news.py
  financial_assistant/src/utilities.py
  financial_assistant/streamlit/app.py
  financial_assistant/streamlit/app_financial_filings.py
  financial_assistant/streamlit/app_pdf_report.py
  financial_assistant/streamlit/app_stock_data.py
  financial_assistant/streamlit/app_stock_database.py
  financial_assistant/streamlit/app_yfinance_news.py
  financial_assistant/streamlit/utilities_app.py
  financial_assistant/streamlit/utilities_methods.py
  financial_assistant/tests/financial_assistant_test.py
Labels: improvement

#468 bugfix multimodal kit and sambastudio input credentials
  multimodal_knowledge_retriever/prompts/llama3-knowledge_retriever_custom_qa_prompt.yaml
  multimodal_knowledge_retriever/prompts/multimodal-qa.yaml
  multimodal_knowledge_retriever/src/multimodal_rag.py
  multimodal_knowledge_retriever/streamlit/app.py
  search_assistant/streamlit/app.py
Labels: bugfix

#469 Bugfix: bug fix when using streaming url
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/src/performance_evaluation.py
Labels: bugfix

#467 Feature: Add api function calling tests for sncloud
  utils/model_wrappers/tests/model_wrappers_test.py
  utils/model_wrappers/tests/schemas.py
  utils/model_wrappers/tests/utils_test.py
Labels: feature

#472 Improvement: update model wrappers
  benchmarking/src/llmperf/sambanova_client.py
  utils/model_wrappers/langchain_chat_models.py
  utils/model_wrappers/langchain_llms.py
  utils/model_wrappers/multimodal_models.py
  utils/model_wrappers/tests/model_wrappers_test.py
Labels: improvement

#461 changed definitions related to throughput
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
Labels: documentation, improvement

#456 Documentation: Update model name instructions
  benchmarking/README.md
Labels: documentation

#471 Improvement: benchmarking persist prompt bins
  benchmarking/requirements.txt
  benchmarking/src/performance_evaluation.py
Labels: improvement

#470 Feature: scribe qwen2
  sambanova_scribe/config.yaml
  sambanova_scribe/data/base.mp3
  sambanova_scribe/data/reddit_sample1.mp3
  sambanova_scribe/data/reddit_sample2.mp3
  sambanova_scribe/data/reddit_sample3.mp3
  sambanova_scribe/data/sample_record.mp3
  sambanova_scribe/data/sample_record_2.mp3
  sambanova_scribe/notebooks/speech_asr_and_reasoning.ipynb
  sambanova_scribe/requirements.txt
  sambanova_scribe/src/scribe.py
  sambanova_scribe/streamlit/app.py
  sambanova_scribe/streamlit/st_utils.py
Labels: improvement, feature

#473 Feature: CrewAI Integration
  integrations/crewai/Agentic_Sales_Pipeline_Crew_AI.ipynb
  integrations/crewai/config/email_engagement_agents.yaml
  integrations/crewai/config/email_engagement_tasks.yaml
  integrations/crewai/config/lead_qualification_agents.yaml
  integrations/crewai/config/lead_qualification_tasks.yaml
  integrations/crewai/crewai_flow.html
  integrations/crewai/requirements.txt
  integrations/crewai/utils.py
Labels: feature

#474 Improvement: Guardrails and quickstart update
  README.md
  quickstart/README.md
  sambanova_scribe/README.md
  sambanova_scribe/docs/sambanova_scribe_app.png
  utils/guardrails/README.md
  utils/guardrails/guard.ipynb
  utils/guardrails/guard.py
  utils/guardrails/requirements.txt
Labels: improvement

#475 Bugfix/benchmarking racing per user
  benchmarking/src/performance_evaluation.py
  benchmarking/streamlit/pages/custom_performance_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
  benchmarking/streamlit/streamlit_utils.py
Labels: bugfix

#476 bugfix: scribe updated requirements
  base-requirements.txt
  function_calling/src/function_calling.py
Labels: bugfix

#477 Bugfix/benchmarking racing per user
  benchmarking/requirements.txt
  benchmarking/streamlit/pages/custom_performance_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
Labels: bugfix, improvement

#478 Improvement/scribe update
  sambanova_scribe/data/reddit_sample1.mp3
  sambanova_scribe/data/reddit_sample2.mp3
  sambanova_scribe/data/reddit_sample3.mp3
  sambanova_scribe/data/sample_yt_cookies.txt
  sambanova_scribe/src/scribe.py
Labels: improvement

#479 Improvement: update scribe notebook cell executions
  sambanova_scribe/notebooks/speech_asr_and_reasoning.ipynb
Labels: improvement

#480 Feature: Camel integration
  integrations/camel/Customer_Service_Discord_Bot_with_Agentic_RAG_Powered_by_Qwen_models_served_by_SambaNova,_using_🐫_CAMEL,_Firecrawl_&_Qdrant_.ipynb
  integrations/camel/imgs/chat1.png
  integrations/camel/imgs/chat2.png
  integrations/camel/imgs/chat3.png
  integrations/camel/imgs/chat4.png
  integrations/camel/imgs/workflow.png
  integrations/camel/requirements.txt
Labels: feature

#481 documentation: updated model list in quickstart
  quickstart/README.md
Labels: documentation

#484 Improvement: kits stremlit pages enhancements
  enterprise_knowledge_retriever/src/document_retrieval.py
  enterprise_knowledge_retriever/streamlit/app.py
  enterprise_knowledge_retriever/streamlit/app_description.yaml
  multimodal_knowledge_retriever/README.md
  multimodal_knowledge_retriever/src/multimodal_rag.py
  multimodal_knowledge_retriever/streamlit/app.py
  multimodal_knowledge_retriever/streamlit/app_description.yaml
  search_assistant/streamlit/app.py
  search_assistant/streamlit/app_description.yaml
Labels: improvement

#482 Improvement: Partial update to Llama3.3
  benchmarking/README.md
  benchmarking/run_custom_dataset.sh
  benchmarking/run_synthetic_dataset.sh
  benchmarking/src/chat_performance_evaluation.py
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/streamlit/pages/chat_performance_st.py
  benchmarking/streamlit/pages/custom_performance_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
  financial_assistant/config.yaml
  post_call_analysis/config.yaml
  prompt_engineering/config.yaml
  sambanova_scribe/config.yaml
  web_crawled_data_retriever/config.yaml
Labels: improvement

#483 Improvement: Update landing page and requirements
  base-requirements.txt
  data_extraction/requirements.txt
  data_extraction/requirementsPaddle.txt
  enterprise_knowledge_retriever/requirements.txt
  financial_assistant/README.md
  financial_assistant/constants.py
  financial_assistant/requirements.txt
  financial_assistant/src/retrieval.py
  financial_assistant/streamlit/app.py
  financial_assistant/streamlit/utilities_methods.py
  function_calling/requirements.txt
  multimodal_knowledge_retriever/requirements.txt
  post_call_analysis/requirements.txt
  search_assistant/requirements.txt
  utils/model_wrappers/api_gateway.py
  web_crawled_data_retriever/requirements.txt
Labels: improvement

#453 Feature: RAG eval feature
  eval_jumpstart/README.md
  eval_jumpstart/data/eval_set_slim.csv
  eval_jumpstart/data/rag_data.csv
  eval_jumpstart/data/sambanova_dataflow_coe.pdf
  eval_jumpstart/notebooks/eval_llm.ipynb
  eval_jumpstart/requirements.txt
  eval_jumpstart/streamlit/app.py
  eval_jumpstart/streamlit/app_description.yaml
  utils/eval/config.yaml
  utils/eval/dataset.py
  utils/eval/evaluator.py
  utils/eval/models.py
  utils/eval/prompts/judge_prompt.py
  utils/eval/prompts/system_prompt.py
  utils/eval/rag.py
  utils/eval/schemas.py
  utils/eval/vector_store.py
Labels: feature
