Repository sambanova/ai-starter-kit, pull requests merged in 2025-06, with the labels that each got.

#719 Improvement: Benchmarking setup screen on side bar
  benchmarking/streamlit/app.py
  benchmarking/streamlit/pages/chat_performance_st.py
  benchmarking/streamlit/pages/custom_performance_eval_st.py
  benchmarking/streamlit/pages/real_workload_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
  benchmarking/streamlit/streamlit_utils.py
  utils/visual/env_utils.py
Labels: bugfix, improvement

#722 Bugfix: fixed mp_events initialization in Benchmarking kit
  benchmarking/streamlit/app.py
  benchmarking/streamlit/pages/chat_performance_st.py
  benchmarking/streamlit/pages/custom_performance_eval_st.py
  benchmarking/streamlit/pages/real_workload_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
  benchmarking/streamlit/streamlit_utils.py
Labels: bugfix

#728 Improvement: Update the financial assistant streamlit app for AISK rebranding
  financial_assistant/streamlit/app.py
Labels: improvement

#729 Improvement: Update the financial assistant streamlit app for AISK rebranding
  financial_assistant/streamlit/app.py
Labels: improvement
