Repository sambanova/ai-starter-kit, pull requests merged in 2025-03, with the labels that each got.

#549 Documentation: update README.md
  e2e_fine_tuning/README.md
Labels: documentation

#552 Improvement: EKR and Search assistant improvements
  enterprise_knowledge_retriever/src/document_retrieval.py
  enterprise_knowledge_retriever/streamlit/app.py
  search_assistant/src/search_assistant.py
Labels: bugfix, improvement

#553 Improvement: Changed Threadpoolexecutor to support more than default threads
  benchmarking/src/performance_evaluation.py
Labels: improvement

#555 docs: update quickstart model list
  quickstart/README.md
Labels: documentation

#556 Improvement: Flexbility to change prompts
  benchmarking/src/performance_evaluation.py
Labels: improvement

#557 Benchmarking: Acceptance rate added
  benchmarking/src/llmperf/common_metrics.py
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/src/performance_evaluation.py
Labels: improvement

#560 Improvement: Added completion_tokens_after_first_per_sec_first_ten
  benchmarking/src/llmperf/common_metrics.py
  benchmarking/src/llmperf/sambanova_client.py
Labels: improvement

#561 Bugfix/search assistant vectordb
  search_assistant/config.yaml
  search_assistant/requirements.txt
  search_assistant/src/search_assistant.py
  search_assistant/streamlit/app.py
  utils/vectordb/vector_db.py
Labels: bugfix

#564 Improvement: Benchmarking with download button in Synthetic Perf Eval
  benchmarking/benchmarking_studio/real_workload_compiler_results.ipynb
  benchmarking/benchmarking_studio/synthetic_compare_different_providers.ipynb
  benchmarking/benchmarking_studio/synthetic_compiler_results.ipynb
  benchmarking/config.yaml
  benchmarking/src/performance_evaluation.py
  benchmarking/streamlit/app.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
  benchmarking/streamlit/streamlit_utils.py
  utils/visual/env_utils.py
Labels: improvement, feature

#566 [bugfix] Multimodal RAG notebook
  multimodal_knowledge_retriever/notebooks/2_multimodal_rag.ipynb
Labels: bugfix

#567 Improvement/benchmarking remove batch size one on cloud
  benchmarking/README.md
  benchmarking/notebooks/analyze-results.ipynb
  benchmarking/run_custom_dataset.sh
  benchmarking/run_real_workload_dataset.sh
  benchmarking/run_synthetic_dataset.sh
  benchmarking/streamlit/pages/custom_performance_eval_st.py
  benchmarking/streamlit/pages/real_workload_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
  benchmarking/streamlit/streamlit_utils.py
Labels: improvement

#568 Feature: Add dependabot checks
  .github/workflows/dependabot.yml
Labels: feature

#570 Bugfix: Move dependabot out of workflows
  .github/dependabot.yml
Labels: bugfix

#550 Bugfix: e2e finetuning and deployment issues
  e2e_fine_tuning/deploy_config.yaml
  e2e_fine_tuning/finetune_config.yaml
  e2e_fine_tuning/notebooks/3_fine_tuning.ipynb
  e2e_fine_tuning/notebooks/4_deploy.ipynb
  utils/fine_tuning/src/snsdk_wrapper.py
Labels: bugfix

#551 First draft of crewai integrated travel planner
  base-requirements.txt
  integrations/crewai/travel_planner_crew_sambanova/README.md
  integrations/crewai/travel_planner_crew_sambanova/app.py
  integrations/crewai/travel_planner_crew_sambanova/config/address_agents.yaml
  integrations/crewai/travel_planner_crew_sambanova/config/address_tasks.yaml
  integrations/crewai/travel_planner_crew_sambanova/config/agents.yaml
  integrations/crewai/travel_planner_crew_sambanova/config/tasks.yaml
  integrations/crewai/travel_planner_crew_sambanova/crew.py
  integrations/crewai/travel_planner_crew_sambanova/db.py
  integrations/crewai/travel_planner_crew_sambanova/requirements.txt
Labels: improvement

#576 Improvement: Benchmarking Threadpoolexecutor
  benchmarking/src/performance_evaluation.py
Labels: improvement

#655 Improvement: Updated readme
  benchmarking/README.md
  benchmarking/streamlit/pages/chat_performance_st.py
Labels: documentation, improvement

#660 Feature: Remove wandb logging
  enterprise_knowledge_retriever/src/document_retrieval.py
  function_calling/src/function_calling.py
  search_assistant/src/search_assistant.py
  tests/test_framework.py
Labels: feature

#531 Feature: eval kit metrics
  base-requirements.txt
  enterprise_knowledge_retriever/tests/ekr_test.py
  eval_jumpstart/requirements.txt
  eval_jumpstart/streamlit/app_description.yaml
  utils/eval/config.yaml
  utils/eval/eval_utils.py
  utils/eval/evaluator.py
  utils/eval/models.py
  utils/eval/rag.py
Labels: improvement

#661 Bugfix: Lowered threshold in EKR test
  enterprise_knowledge_retriever/tests/ekr_test.py
Labels: bugfix

#659 Improvement: Benchmarking update in tokenizers
  base-requirements.txt
  benchmarking/README.md
  benchmarking/requirements.txt
  benchmarking/run_synthetic_dataset.sh
  benchmarking/src/chat_performance_evaluation.py
  benchmarking/src/llmperf/llmperf_utils.py
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/src/performance_evaluation.py
  benchmarking/streamlit/pages/real_workload_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
Labels: improvement

#656 A couple of bug fixes that crept into PR #551
  integrations/crewai/travel_planner_crew_sambanova/app.py
  integrations/crewai/travel_planner_crew_sambanova/crews/config/address_agents.yaml
  integrations/crewai/travel_planner_crew_sambanova/crews/config/address_tasks.yaml
  integrations/crewai/travel_planner_crew_sambanova/crews/config/agents.yaml
  integrations/crewai/travel_planner_crew_sambanova/crews/config/tasks.yaml
  integrations/crewai/travel_planner_crew_sambanova/crews/crew.py
Labels: bugfix
