Repository sambanova/ai-starter-kit, pull requests merged in 2025-05, with the labels that each got.

#698 Bugfix: Ruff toml and format changes
  benchmarking/src/chat_performance_evaluation.py
  benchmarking/src/evaluator.py
  benchmarking/src/llmperf/llmperf_utils.py
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/src/performance_evaluation.py
  benchmarking/streamlit/app.py
  benchmarking/streamlit/pages/chat_performance_st.py
  benchmarking/streamlit/pages/custom_performance_eval_st.py
  benchmarking/streamlit/pages/real_workload_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
  benchmarking/streamlit/streamlit_utils.py
  enterprise_knowledge_retriever/tests/ekr_test.py
  ruff.toml
  utils/eval/models.py
  utils/fine_tuning/src/snsdk_wrapper.py
  utils/visual/env_utils.py
Labels: bugfix

#671 Improvement: Benchmarking tracking models
  benchmarking/benchmarking_scripts/config.yaml
  benchmarking/benchmarking_scripts/model_configs_example.csv
  benchmarking/benchmarking_scripts/synthetic_performance_eval_script.py
  benchmarking/benchmarking_studio/real_workload_compiler_results.ipynb
  benchmarking/benchmarking_studio/real_workload_performance_eval_script.py
  benchmarking/benchmarking_studio/synthetic_compare_different_providers.ipynb
  benchmarking/benchmarking_studio/synthetic_compiler_results.ipynb
  benchmarking/benchmarking_studio/synthetic_performance_eval_script.py
  benchmarking/config.yaml
  benchmarking/notebooks/analyze-results.ipynb
  benchmarking/notebooks/compare_different_providers.ipynb
  benchmarking/notebooks/multiple-models-benchmark.ipynb
  benchmarking/src/llmperf/llmperf_utils.py
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/src/performance_evaluation.py
  benchmarking/streamlit/app.py
  benchmarking/streamlit/pages/custom_performance_eval_st.py
  benchmarking/streamlit/pages/real_workload_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
  benchmarking/streamlit/streamlit_utils.py
  benchmarking/utils.py
  tests/test_framework.py
Labels: improvement

#699 Improvement: Update requirements in financial_assistant
  financial_assistant/README.md
  financial_assistant/requirements.txt
Labels: improvement

#705 Improvement: Update requirements financial agent
  financial_agent_crewai/README.md
  financial_agent_crewai/requirements.txt
  financial_agent_crewai/src/financial_agent_flow/tools/yfinance_stocks_tools.py
Labels: improvement

#707 Improvement: Added ignore_eos param to cloud api class
  benchmarking/src/llmperf/sambanova_client.py
Labels: improvement

#706 Improvement: Benchmarking TTFT and benchmarking scripts changes
  benchmarking/benchmarking_scripts/synthetic_performance_eval_script.py
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/src/performance_evaluation.py
Labels: bugfix, improvement

#711 Bugfix: Financial agent crewai
  financial_agent_crewai/README.md
  financial_agent_crewai/pyproject.toml
  financial_agent_crewai/requirements.txt
  financial_agent_crewai/src/financial_agent_flow/main.py
  financial_agent_crewai/src/financial_agent_flow/tools/sec_edgar_tools.py
  flow.html
Labels: bugfix

#713 Improvement: Added use debugging flag
  benchmarking/README.md
  benchmarking/benchmarking_scripts/synthetic_performance_eval_script.py
  benchmarking/run_custom_dataset.sh
  benchmarking/run_real_workload_dataset.sh
  benchmarking/run_synthetic_dataset.sh
  benchmarking/src/evaluator.py
  benchmarking/src/llmperf/models.py
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/src/performance_evaluation.py
Labels: improvement
