Repository sambanova/ai-starter-kit, pull requests merged in 2025-01, with the labels that each got.

#490 omit financial assistant tests
  tests/test_framework.py
Labels: bugfix

#485 Improvement/scribe default endpoint
  sambanova_scribe/README.md
  sambanova_scribe/src/scribe.py
  sambanova_scribe/streamlit/app.py
Labels: improvement

#486 Improvement/e2e byoc ft
  e2e_fine_tuning/checkpoints_config.yaml
  e2e_fine_tuning/deploy_config.yaml
  e2e_fine_tuning/finetune_config.yaml
  e2e_fine_tuning/notebooks/1_checkpoints.ipynb
  e2e_fine_tuning/notebooks/2_datasets.ipynb
  e2e_fine_tuning/notebooks/3_fine_tuning.ipynb
  e2e_fine_tuning/notebooks/4_deploy.ipynb
  utils/byoc/src/snsdk_byoc_wrapper.py
  utils/fine_tuning/src/snsdk_wrapper.py
  utils/fine_tuning/usage.ipynb
Labels: bugfix, improvement

#488 Improvement: crewai updates
  integrations/crewai/Agentic_Sales_Pipeline_Crew_AI.ipynb
  integrations/crewai/crewai_flow.html
  integrations/crewai/requirements.txt
  integrations/crewai/utils.py
Labels: improvement

#492 Bugfix: Reset the default year to 2023 SEC EDGAR filings
  financial_assistant/constants.py
  financial_assistant/streamlit/app_financial_filings.py
  tests/test_framework.py
Labels: bugfix

#495 CrewAI integration update
  integrations/crewai/Agentic_Sales_Pipeline_Crew_AI.ipynb
  integrations/crewai/crewai_flow.png
  integrations/crewai/requirements.txt
Labels: improvement

#498 Feature: Crewai Research Assistant Demo
  integrations/crewai/edu_planner_crew_sambanova/.gitignore
  integrations/crewai/edu_planner_crew_sambanova/README.md
  integrations/crewai/edu_planner_crew_sambanova/crewai_flow.html
  integrations/crewai/edu_planner_crew_sambanova/pyproject.toml
  integrations/crewai/edu_planner_crew_sambanova/requirements.txt
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/__init__.py
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/config.py
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/crews/edu_content_writer/config/agents.yaml
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/crews/edu_content_writer/config/tasks.yaml
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/crews/edu_content_writer/edu_content_writer_crew.py
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/crews/edu_research/config/agents.yaml
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/crews/edu_research/config/tasks.yaml
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/crews/edu_research/edu_research_crew.py
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/llm_config.py
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/main.py
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/streamlit_app.py
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/tools/__init__.py
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/tools/custom_tool.py
  integrations/crewai/edu_planner_crew_sambanova/uv.lock
  mypy.ini
Labels: feature

#500 Reorganize crewAI integration folder
  integrations/crewai/sales_pipeline_crew_sambanova/Agentic_Sales_Pipeline_Crew_AI.ipynb
  integrations/crewai/sales_pipeline_crew_sambanova/config/email_engagement_agents.yaml
  integrations/crewai/sales_pipeline_crew_sambanova/config/email_engagement_tasks.yaml
  integrations/crewai/sales_pipeline_crew_sambanova/config/lead_qualification_agents.yaml
  integrations/crewai/sales_pipeline_crew_sambanova/config/lead_qualification_tasks.yaml
  integrations/crewai/sales_pipeline_crew_sambanova/crewai_flow.html
  integrations/crewai/sales_pipeline_crew_sambanova/crewai_flow.png
  integrations/crewai/sales_pipeline_crew_sambanova/requirements.txt
Labels: improvement

#493 Improvement: tmp folder per session in EKR
  enterprise_knowledge_retriever/requirements.txt
  enterprise_knowledge_retriever/streamlit/app.py
Labels: bugfix, improvement

#497 Feature: Add haystack integration
  integrations/README.md
  integrations/haystack/haystack_sambanova_examples.ipynb
Labels: feature

#494 improvement: format description for get time tool
  function_calling/src/tools.py
Labels: bugfix, improvement

#502 Improvement: streaming tool calling support LangChain wrapper
  utils/model_wrappers/langchain_chat_models.py
Labels: improvement

#505 remove outdated video
  enterprise_knowledge_retriever/README.md
Labels: documentation

#496 Feature: EKR quality test and eval minor improvements
  enterprise_knowledge_retriever/tests/data/rag_data.csv
  enterprise_knowledge_retriever/tests/data/test/sambanova_dataflow_coe.pdf
  enterprise_knowledge_retriever/tests/ekr_test.py
  eval_jumpstart/streamlit/app.py
  utils/eval/config.yaml
  utils/eval/evaluator.py
  utils/eval/models.py
  utils/eval/prompts/judge_prompt.py
  utils/eval/rag.py
Labels: feature

#508 Bugfix: EKR chat output format
  enterprise_knowledge_retriever/README.md
  enterprise_knowledge_retriever/streamlit/app.py
Labels: bugfix, documentation

#511 Feature: Autogen integration examples
  integrations/autogen/company-research.ipynb
  integrations/autogen/requirements.txt
  integrations/autogen/travel-planning.ipynb
Labels: feature

#513 Improvement: Streamlit error messages and progress bar
  benchmarking/run_custom_dataset.sh
  benchmarking/run_synthetic_dataset.sh
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/src/performance_evaluation.py
  benchmarking/streamlit/pages/custom_performance_eval_st.py
  benchmarking/streamlit/pages/synthetic_performance_eval_st.py
Labels: bugfix, improvement

#517 Improvement: EKR model selector
  enterprise_knowledge_retriever/src/document_retrieval.py
  enterprise_knowledge_retriever/streamlit/app.py
  multimodal_knowledge_retriever/streamlit/app.py
Labels: improvement
