Repository sambanova/ai-starter-kit, pull requests merged in 2025-04, with the labels that each got.

#664 Bugfix: Remove image search unit test from test_framework.py
  tests/test_framework.py
Labels: bugfix

#662 Feature: Add spec decoding to Snsdkwrapper
  e2e_fine_tuning/notebooks/5_spec_decoding.ipynb
  e2e_fine_tuning/spec_decoding_config.yaml
  utils/fine_tuning/src/snsdk_wrapper.py
Labels: feature

#666 bugfix: postcall analysis tests
  base-requirements.txt
  multimodal_knowledge_retriever/requirements.txt
  multimodal_knowledge_retriever/tests/multimodal_knowledge_retriever_test.py
  post_call_analysis/requirements.txt
  search_assistant/requirements.txt
  tests/test_framework.py
  web_crawled_data_retriever/requirements.txt
Labels: bugfix

#669 Improvement: Benchmarking custom eval with default prompt
  benchmarking/README.md
  benchmarking/prompts/custom_prompt_example.jsonl
  benchmarking/src/performance_evaluation.py
Labels: bugfix, improvement

#672 Documentation: Added warning about stopping kit on heavy runs
  benchmarking/README.md
Labels: documentation, improvement

#574 improvement: update AISK models
  README.md
  benchmarking/README.md
  benchmarking/benchmarking_studio/real_workload_performance_eval_script.py
  benchmarking/benchmarking_studio/synthetic_performance_eval_script.py
  benchmarking/run_synthetic_dataset.sh
  bundle_jump_start/README.md
  bundle_jump_start/config.yaml
  enterprise_knowledge_retriever/config.yaml
  enterprise_knowledge_retriever/streamlit/app.py
  eval_jumpstart/README.md
  financial_assistant/config.yaml
  multimodal_knowledge_retriever/config.yaml
  multimodal_knowledge_retriever/streamlit/app.py
  quickstart/README.md
  quickstart/function_calling_get_started.ipynb
  sambanova_scribe/notebooks/speech_asr_and_reasoning.ipynb
  search_assistant/config.yaml
  tests/test_framework.py
  utils/eval/config.yaml
  utils/model_wrappers/tests/model_wrappers_test.py
  utils/model_wrappers/tests/test_config.yaml
  utils/model_wrappers/usage.ipynb
  utils/tests/config.yaml
Labels: documentation

#674 Improvement: Add 0.05 pctl to summary file and summary stats on analysis notebook
  benchmarking/README.md
  benchmarking/notebooks/analyze-results.ipynb
  benchmarking/src/performance_evaluation.py
Labels: improvement

#673 Improvement: Update Synthetic Data Gen Notebook
  utils/synthetic_data_gen/notebooks/quickstart_synthetic_data_gen.ipynb
Labels: improvement

#675 Improvement: Benchmarking deployment credentials order
  search_assistant/requirements.txt
  utils/visual/env_utils.py
Labels: improvement

#677 fix bug: llm model not being set in ekr
  enterprise_knowledge_retriever/src/document_retrieval.py
Labels: bugfix

#676 Improvement: Update Synthetic Data Gen Src files
  utils/synthetic_data_gen/config.yaml
  utils/synthetic_data_gen/notebooks/usage.ipynb
  utils/synthetic_data_gen/requirements.txt
  utils/synthetic_data_gen/src/synthetic_data_gen.py
Labels: improvement

#685 improvement: update multimodal models
  multimodal_knowledge_retriever/config.yaml
  multimodal_knowledge_retriever/notebooks/1_multimodal_get_started.ipynb
  multimodal_knowledge_retriever/notebooks/2_multimodal_rag.ipynb
  multimodal_knowledge_retriever/requirements.txt
  multimodal_knowledge_retriever/streamlit/app.py
  quickstart/README.md
  quickstart/multimodal_get_started.ipynb
  utils/tests/api_testing.py
  utils/tests/config.yaml
Labels: improvement

#687 Update README.md multimodal kit
  multimodal_knowledge_retriever/README.md
Labels: documentation

#684 Improvement: Benchmarking support for Llama4
  benchmarking/README.md
  benchmarking/src/llmperf/llmperf_utils.py
Labels: documentation, improvement

#689 Improvement: Added header for debug mode on cloud
  benchmarking/src/llmperf/sambanova_client.py
  tests/test_framework.py
Labels: improvement

#688 Bug Fix: Fixed bug related to custom urls
  base-requirements.txt
  utils/visual/env_utils.py
Labels: bugfix

#691 Bug fix: Removed blank in custom eval prefix prompt
  benchmarking/src/performance_evaluation.py
Labels: bugfix

#692 Bugfix: Reverted milvus back after fix
  base-requirements.txt
  document_comparison/requirements.txt
  enterprise_knowledge_retriever/requirements.txt
  eval_jumpstart/requirements.txt
  function_calling/requirements.txt
  multimodal_knowledge_retriever/requirements.txt
  post_call_analysis/requirements.txt
  search_assistant/requirements.txt
  utils/vectordb/vector_db.py
  web_crawled_data_retriever/requirements.txt
Labels: bugfix

#693 Feature: Add saving feature for LLM generations in Benchmarking CLI synthetic perf eval
  benchmarking/README.md
  benchmarking/run_synthetic_dataset.sh
  benchmarking/src/evaluator.py
  benchmarking/src/performance_evaluation.py
Labels: feature

#562 Improvement: Improve prompts for different perf qualities
  benchmarking/README.md
  benchmarking/prompts/user-prompt_template-text_instruct.yaml
  benchmarking/prompts/user-prompt_template-vision_instruct.yaml
  benchmarking/run_custom_dataset.sh
  benchmarking/run_synthetic_dataset.sh
  benchmarking/src/chat_performance_evaluation.py
  benchmarking/src/evaluator.py
  benchmarking/src/llmperf/common_metrics.py
  benchmarking/src/llmperf/models.py
  benchmarking/src/llmperf/sambanova_client.py
  benchmarking/src/performance_evaluation.py
  tests/test_framework.py
Labels: improvement
