Repository sambanova/ai-starter-kit, pull requests merged in 2025-02, with the labels that each got.

#519 Improvement: show full error details in EKR ingestion if not prod mode and basic error logging
  enterprise_knowledge_retriever/streamlit/app.py
Labels: improvement

#516 Feature: Added example with semantic kernel integration
  integrations/semantic_kernel/agents_solving_task.ipynb
  integrations/semantic_kernel/requirements.txt
Labels: feature

#515 Feature: Benchmarking - OpenAI compatible and comparison
  benchmarking/README.md
  benchmarking/benchmarking_studio/compare_different_providers.ipynb
  benchmarking/benchmarking_studio/compiler_results.ipynb
  benchmarking/src/llmperf/sambanova_client.py
Labels: feature

#524 improvement: guardrails util notebook updated
  utils/guardrails/guard.ipynb
  utils/guardrails/guard.py
  utils/guardrails/requirements.txt
Labels: improvement

#512 Improvement: Document comparison tests added
  document_comparison/src/document_analyzer.py
  document_comparison/streamlit/app.py
  document_comparison/templates/document_comparison_templates.json
  document_comparison/tests/data/SN40LPaper2Pages.pdf
  document_comparison/tests/data/test_case.yaml
  document_comparison/tests/dc_test.py
  integrations/crewai/edu_planner_crew_sambanova/uv.lock
  tests/test_framework.py
Labels: improvement

#522 improvement: add deepseek R1 distilled llama70B and Tulu3 405B to models lists
  enterprise_knowledge_retriever/streamlit/app.py
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/config.py
  multimodal_knowledge_retriever/streamlit/app.py
  quickstart/README.md
Labels: improvement

#526 improvement: update code copilot docs and models
  README.md
  code_copilot/README.md
  code_copilot/config.json
Labels: improvement

#525 Improvement: update upload limit label ekr streamlit
  enterprise_knowledge_retriever/streamlit/app.py
Labels: improvement

#527 Remove YoDa kit
  README.md
  yoda/README.md
  yoda/data/sambanova_resources_blogs/blog_generative-ai-for-enterprise-and-government.txt
  yoda/data/sambanova_resources_blogs/blog_generative-ai-terms.txt
  yoda/data/sambastudio/sambastudio_add-datasets.txt
  yoda/data/sambastudio/sambastudio_cli-setup.txt
  yoda/prompts/llama3_1-create-tableqa.yaml
  yoda/prompts/llama3_1-modify-table.yaml
  yoda/prompts/llama3_1-table-ocr.yaml
  yoda/prompts/prompts.py
  yoda/prompts/table_qa_template.py
  yoda/requirements.txt
  yoda/scripts/preprocess.sh
  yoda/sn_expert_conf.yaml
  yoda/src/__init__.py
  yoda/src/evaluate.py
  yoda/src/gen_data.py
  yoda/tools/__init__.py
  yoda/tools/data_reader.py
  yoda/tools/qa_processing.py
Labels: improvement

#529 Integrations ReadMe additions
  integrations/README.md
Labels: documentation

#528 Feature: Add guardrails benchmark notebook
  README.md
  base-requirements.txt
  code_copilot/README.md
  code_copilot/config.json
  document_comparison/src/document_analyzer.py
  document_comparison/streamlit/app.py
  document_comparison/templates/document_comparison_templates.json
  document_comparison/tests/data/SN40LPaper2Pages.pdf
  document_comparison/tests/data/test_case.yaml
  document_comparison/tests/dc_test.py
  enterprise_knowledge_retriever/streamlit/app.py
  integrations/README.md
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/config.py
  integrations/crewai/edu_planner_crew_sambanova/uv.lock
  multimodal_knowledge_retriever/streamlit/app.py
  quickstart/README.md
  tests/test_framework.py
  utils/tests/api_testing.py
  utils/tests/config.yaml
  utils/tests/data/sample.png
  utils/tests/data/samplerecord.mp3
  utils/tests/utils_test.py
  yoda/README.md
  yoda/data/sambanova_resources_blogs/blog_generative-ai-for-enterprise-and-government.txt
  yoda/data/sambanova_resources_blogs/blog_generative-ai-terms.txt
  yoda/data/sambastudio/sambastudio_add-datasets.txt
  yoda/data/sambastudio/sambastudio_cli-setup.txt
  yoda/prompts/llama3_1-create-tableqa.yaml
  yoda/prompts/llama3_1-modify-table.yaml
  yoda/prompts/llama3_1-table-ocr.yaml
  yoda/prompts/prompts.py
  yoda/prompts/table_qa_template.py
  yoda/requirements.txt
  yoda/scripts/preprocess.sh
  yoda/sn_expert_conf.yaml
  yoda/src/__init__.py
  yoda/src/evaluate.py
  yoda/src/gen_data.py
  yoda/tools/__init__.py
  yoda/tools/data_reader.py
  yoda/tools/qa_processing.py
Labels: feature

#532 Workaround for CoE model
  benchmarking/src/llmperf/sambanova_client.py
Labels: bugfix, improvement

#530 improvement: e2e fine-tuning streamlined execution
  e2e_fine_tuning/notebooks/3_fine_tuning.ipynb
Labels: improvement

#520 Feature: CrewAI Financial Agent
  .gitignore
  base-requirements.txt
  document_comparison/tests/dc_test.py
  eval_jumpstart/streamlit/app.py
  financial_agent_crewai/.gitignore
  financial_agent_crewai/README.md
  financial_agent_crewai/flow.html
  financial_agent_crewai/main.py
  financial_agent_crewai/pyproject.toml
  financial_agent_crewai/requirements.txt
  financial_agent_crewai/src/__init__.py
  financial_agent_crewai/src/financial_agent_crewai/config.py
  financial_agent_crewai/src/financial_agent_crewai/crews/context_analysis_crew/config/agents.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/context_analysis_crew/config/tasks.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/context_analysis_crew/context_analysis_crew.py
  financial_agent_crewai/src/financial_agent_crewai/crews/decomposition_crew/config/agents.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/decomposition_crew/config/tasks.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/decomposition_crew/decomposition_crew.py
  financial_agent_crewai/src/financial_agent_crewai/crews/generic_research_crew/config/agents.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/generic_research_crew/config/tasks.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/generic_research_crew/generic_research_crew.py
  financial_agent_crewai/src/financial_agent_crewai/crews/rag_crew/config/agents.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/rag_crew/config/tasks.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/rag_crew/rag_crew.py
  financial_agent_crewai/src/financial_agent_crewai/crews/report_crew/config/agents.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/report_crew/config/tasks.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/report_crew/report_crew.py
  financial_agent_crewai/src/financial_agent_crewai/crews/sec_edgar_crew/config/agents.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/sec_edgar_crew/config/tasks.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/sec_edgar_crew/sec_edgar_crew.py
  financial_agent_crewai/src/financial_agent_crewai/crews/sorting_hat_crew/config/agents.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/sorting_hat_crew/config/tasks.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/sorting_hat_crew/sorting_hat_crew.py
  financial_agent_crewai/src/financial_agent_crewai/crews/summarization_crew/config/agents.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/summarization_crew/config/tasks.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/summarization_crew/summarization_crew.py
  financial_agent_crewai/src/financial_agent_crewai/crews/yfinance_news_crew/config/agents.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/yfinance_news_crew/config/tasks.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/yfinance_news_crew/yfinance_news_crew.py
  financial_agent_crewai/src/financial_agent_crewai/crews/yfinance_stocks_crew/config/agents.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/yfinance_stocks_crew/config/tasks.yaml
  financial_agent_crewai/src/financial_agent_crewai/crews/yfinance_stocks_crew/yfinance_stocks_crew.py
  financial_agent_crewai/src/financial_agent_crewai/tools/__init__.py
  financial_agent_crewai/src/financial_agent_crewai/tools/general_tools.py
  financial_agent_crewai/src/financial_agent_crewai/tools/rag_tools.py
  financial_agent_crewai/src/financial_agent_crewai/tools/report_tools.py
  financial_agent_crewai/src/financial_agent_crewai/tools/sec_edgar_tools.py
  financial_agent_crewai/src/financial_agent_crewai/tools/sorting_hat_tools.py
  financial_agent_crewai/src/financial_agent_crewai/tools/yfinance_news_tools.py
  financial_agent_crewai/src/financial_agent_crewai/tools/yfinance_stocks_tools.py
  financial_agent_crewai/streamlit/.streamlit/config.toml
  financial_agent_crewai/streamlit/streamlit_app.py
  financial_agent_crewai/utils/utilities.py
  financial_assistant/README.md
  financial_assistant/constants.py
  financial_assistant/requirements.txt
  financial_assistant/src/tools_yahoo_news.py
  image_search/src/image_search.py
  tests/test_framework.py
  utils/guardrails/guard.py
Labels: feature

#537 Update test_framework.py
  tests/test_framework.py
Labels: bugfix

#535 bugfix: e2e fine-tuning update requirements
  e2e_fine_tuning/requirements.txt
Labels: bugfix

#533 Fixed bug to reuse team for multiple different questions
  integrations/autogen/company-research.ipynb
Labels: bugfix

#536 Feature: benchmarking guardrails notebook
  utils/guardrails/benchmarking_guardrails.ipynb
  utils/guardrails/requirements.txt
Labels: feature

#539 Update README.md
  integrations/README.md
Labels: documentation

#518 Improvement: Langchain-Sambanova Update
  .github/workflows/docker-build-and-test.yml
  base-requirements.txt
  benchmarking/requirements.txt
  benchmarking/src/llmperf/sambanova_client.py
  bundle_jump_start/requirements.txt
  data_extraction/requirements.txt
  data_extraction/requirementsPaddle.txt
  document_comparison/config.yaml
  document_comparison/requirements.txt
  document_comparison/src/document_analyzer.py
  e2e_fine_tuning/notebooks/4_deploy.ipynb
  e2e_fine_tuning/requirements.txt
  enterprise_knowledge_retriever/requirements.txt
  enterprise_knowledge_retriever/tests/ekr_test.py
  eval_jumpstart/requirements.txt
  financial_agent_crewai/main.py
  financial_assistant/requirements.txt
  fine_tuning_embeddings/requirements.txt
  fine_tuning_sql/requirements.txt
  function_calling/notebooks/function_calling_guide.ipynb
  function_calling/requirements.txt
  integrations/milvus/langchain_RAG_with_milvus_and_SNCloud.ipynb
  multimodal_knowledge_retriever/requirements.txt
  post_call_analysis/requirements.txt
  prompt_engineering/requirements.txt
  quickstart/function_calling_get_started.ipynb
  quickstart/llms_get_started.ipynb
  sambanova_scribe/requirements.txt
  search_assistant/requirements.txt
  search_assistant/src/search_assistant.py
  utils/eval/models.py
  utils/model_wrappers/api_gateway.py
  utils/model_wrappers/usage.ipynb
  web_crawled_data_retriever/requirements.txt
Labels: improvement

#534 improvement: add DeepSeekR1-671B to model lists
  enterprise_knowledge_retriever/streamlit/app.py
  integrations/crewai/edu_planner_crew_sambanova/src/edu_flow/config.py
  multimodal_knowledge_retriever/streamlit/app.py
  quickstart/README.md
Labels: improvement

#542 Improvement: continue models and docs updated
  README.md
  code_copilot/config.json
  code_copilot/config.ts
  integrations/README.md
  integrations/continue/README.md
  integrations/continue/config.json
Labels: documentation, improvement

#544 Bugfix: Update dependencies, update RAG chain, and reinstate tests for the financial assistant
  base-requirements.txt
  financial_agent_crewai/pyproject.toml
  financial_agent_crewai/requirements.txt
  financial_assistant/constants.py
  financial_assistant/requirements.txt
  financial_assistant/src/retrieval.py
  financial_assistant/src/tools_yahoo_news.py
  financial_assistant/streamlit/app.py
  financial_assistant/tests/financial_assistant_test.py
  tests/test_framework.py
Labels: bugfix

#546 Improvement: changed test model name
  prompt_engineering/tests/prompt_engineering_test.py
  tests/test_framework.py
  utils/tests/api_testing.py
Labels: improvement

#540 Improvement: byoc and fine tuning - snapi init and error handling
  e2e_fine_tuning/README.md
  utils/byoc/README.md
  utils/byoc/requirements.txt
  utils/byoc/src/snsdk_byoc_wrapper.py
  utils/byoc/usage.ipynb
  utils/fine_tuning/Readme.md
  utils/fine_tuning/requirements.txt
  utils/fine_tuning/src/sambastudio_utils.py
  utils/fine_tuning/src/snsdk_wrapper.py
  utils/fine_tuning/usage.ipynb
Labels: improvement

#541 Feature: Added AgentOps integration with example
  integrations/agentops/multiagent_agentops_tracking.ipynb
  integrations/agentops/requirements.txt
Labels: feature

#543 improvement: update docs
  README.md
  quickstart/README.md
Labels: documentation
